#!/usr/bin/env Rscript
# Figure 4: source of the stability difference.
# Reads numerical outputs generated by R/reproduce_manuscript.R.

ladder <- c("UNC","CSF","TC","ATC","CR")
vc <- read.csv(file.path("outputs","variance_components.csv"), stringsAsFactors=FALSE)
tv <- read.csv(file.path("outputs","tissue_explained_variance.csv"), stringsAsFactors=FALSE)
ri <- read.csv(file.path("outputs","tissue_residualized_icc.csv"), stringsAsFactors=FALSE)

get_vc <- function(met, value) {
  d <- vc[vc$metabolite == met, ]
  d <- d[match(ladder, d$measure), ]
  d[[value]]
}
gaba_B   <- get_vc("GABA","cv_between")
gaba_W   <- get_vc("GABA","cv_within")
gaba_ICC <- get_vc("GABA","icc")
glx_B    <- get_vc("Glx","cv_between")
glx_W    <- get_vc("Glx","cv_within")
glx_ICC  <- get_vc("Glx","icc")

r2_mean <- function(met, measure) {
  mean(tv$r2_tissue[tv$metabolite == met & tv$measure == measure], na.rm=TRUE)
}
r2 <- rbind(
  UNC = c(r2_mean("GABA","UNC"), r2_mean("Glx","UNC")),
  ATC = c(r2_mean("GABA","ATC"), r2_mean("Glx","ATC"))
)

resid_mean <- function(met) mean(ri$icc_tissue_residualized[ri$metabolite == met], na.rm=TRUE)
part <- matrix(
  c(gaba_ICC[ladder=="UNC"], resid_mean("GABA"), gaba_ICC[ladder=="ATC"],
    glx_ICC[ladder=="UNC"],  resid_mean("Glx"),  glx_ICC[ladder=="ATC"]),
  nrow=3
)

col_btw <- "#1b7a74"
col_wth <- "#9aa0a6"
col_unc <- "#1b7a74"
col_mid <- "#7fb8b3"
col_atc <- "#cfe3e1"

panel_tag <- function(tag) mtext(tag, side=3, line=2.0, adj=0, font=2, cex=1.35)
panel_title <- function(title) mtext(title, side=3, line=0.9, cex=1.0)
grid_y <- function(at) abline(h=at, col="grey88", lwd=0.8)

cv_panel <- function(B,W,ICC,title,tag) {
  x <- seq_along(ladder)
  plot(NA, xlim=c(0.5,length(ladder)+0.7), ylim=c(-0.5,13.0), xaxt="n",
       xlab="", ylab="Coefficient of variation (%)", main="")
  axis(1, at=x, labels=ladder, tick=FALSE)
  grid_y(seq(0,12,2))
  lines(x,W,lty=2,col=col_wth,lwd=2)
  points(x,W,pch=21,bg="white",col=col_wth,cex=1.5,lwd=2)
  lines(x,B,lty=1,col=col_btw,lwd=2.6)
  points(x,B,pch=19,col=col_btw,cex=1.6)
  text(0.82,12.55,"ICC",adj=0,cex=0.70,col="grey35",font=3)
  text(x,11.60,sprintf("%.2f",ICC),cex=0.78,col="grey35")
  panel_tag(tag); panel_title(title)
}

while (dev.cur() > 1) dev.off()
png(file.path("outputs","variance_decomposition.png"),
    width=2400,height=2000,res=300,bg="white")
par(mfrow=c(2,2),mar=c(4.2,4.5,4.3,1.0),mgp=c(2.6,0.8,0),las=1,family="sans")

cv_panel(gaba_B,gaba_W,gaba_ICC,"GABA+","A")
legend("bottomleft",c("Between-subject (signal)","Within-subject (noise)"),
       col=c(col_btw,col_wth),lty=c(1,2),pch=c(19,21),pt.bg="white",
       lwd=2,bty="n",cex=0.82,inset=c(0.02,0.02))
cv_panel(glx_B,glx_W,glx_ICC,"Glx","B")

bp_c <- barplot(r2,beside=TRUE,names.arg=c("GABA+","Glx"),
                col=c(col_unc,col_atc),border=NA,ylim=c(0,0.68),
                ylab=expression(R^2 * ":  metabolite ~ tissue"))
grid_y(seq(0,0.6,0.1))
barplot(r2,beside=TRUE,col=c(col_unc,col_atc),border=NA,add=TRUE,axes=FALSE)
text(as.vector(bp_c),as.vector(r2)+0.018,sprintf("%.2f",as.vector(r2)),
     cex=0.78,col="grey25")
legend("topright",c("Uncorrected","Alpha tissue-corrected"),
       fill=c(col_unc,col_atc),border=NA,bty="n",cex=0.80,inset=0.01)
panel_tag("C"); panel_title("Variance explained by tissue")

bp_d <- barplot(part,beside=TRUE,names.arg=c("GABA+","Glx"),
                col=c(col_unc,col_mid,col_atc),border=NA,ylim=c(0,0.80),
                ylab="Test-retest ICC")
grid_y(seq(0,0.8,0.1))
barplot(part,beside=TRUE,col=c(col_unc,col_mid,col_atc),
        border=NA,add=TRUE,axes=FALSE)
text(as.vector(bp_d),as.vector(part)+0.020,sprintf("%.2f",as.vector(part)),
     cex=0.78,col="grey25")
legend(x=par("usr")[2],y=par("usr")[4]-0.005,
       legend=c("Uncorrected","Uncorrected | tissue removed","Alpha tissue-corrected"),
       fill=c(col_unc,col_mid,col_atc),border=NA,bty="n",xjust=1,yjust=1,
       cex=0.70,y.intersp=0.88)
panel_tag("D"); panel_title("Removing tissue reproduces correction")

invisible(dev.off())
cat("wrote outputs/variance_decomposition.png\n")
